name: 'Run shodo with reviewdog'
description: '🐶 Run shodo with reviewdog on pull requests to improve code review experience.'
author: 'Songmu'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'warning'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  ### Flags for shodo ###
  api_token:
    description: 'Shodo API token'
    required: true
  api_root:
    description: 'Shodo API root'
    required: true
  base_branch:
    description: 'Base branch'
    default: ''
  limit:
    description: 'Maximum files'
    default: '10'
  dir:
    description: 'Directory to be linted relative to the root directory.'
    default: '.'
runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v3
    with:
      fetch-depth: 0
  - run: $GITHUB_ACTION_PATH/action.sh
    shell: bash
    env:
      REVIEWDOG_VERSION: 'v0.14.1'
      GITHUB_TOKEN: '${{ inputs.github_token }}'
      INPUT_LEVEL: '${{ inputs.level }}'
      INPUT_FILTER_MODE: '${{ inputs.filter_mode }}'
      INPUT_FAIL_ON_ERROR: '${{ inputs.fail_on_error }}'
      INPUT_REVIEWDOG_FLAGS: '${{ inputs.reviewdog_flags }}'
      SHODO_API_TOKEN: '${{ inputs.api_token }}'
      SHODO_API_ROOT: '${{ inputs.api_root }}'
      INPUT_BASE_BRANCH: '${{ inputs.base_branch }}'
      INPUT_LIMIT: '${{ inputs.limit }}'
      INPUT_DIR: '${{ inputs.dir }}'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'edit-3'
  color: 'gray-dark'
