name: Test
on: [pull_request]
jobs:
  test-check:
    name: runner / shodo
    runs-on: ubuntu-latest
    steps:
    - uses: ./
      with:
        github_token: ${{ secrets.github_token }}
        api_token: ${{ secrets.SHODO_API_TOKEN }}
        api_root: ${{ secrets.SHODO_API_ROOT }}
